productos/urls.py
from django.conf.urls import url

import views

app_name = "productos"

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/actualizar/', views.editar, name="editar"),    
    url(r'^(?P<pk>[0-9]+)/agregar', views.agregar, name="agregar"),
    url(r'^(?P<pk>[0-9]+)/quitar', views.quitar, name="quitar"),      
    url(r'^(?P<pk>[0-9]+)', views.DetailView.as_view(), name="detail"),
    
    url(r'^nuevo/', views.nuevo, name="nuevo"),        
    url(r'^guardar/', views.guardar, name="guardar"),    
    
#     url(r'^$', views.index, name="index"),    
#     url(r'^(?P<pk>[0-9]+)', views.detail, name="detail"),     

]

tienda/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^productos/', include("productos.urls")),
    url(r'^admin/', admin.site.urls),
]

productos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.CharField(max_length=255)
    categoria = models.CharField(max_length=255)
    precio = models.IntegerField(default=0)
    cantidad = models.IntegerField(default=0)
    
    def __str__(self):
        return self.nombre

productos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
# Create your views here.

from models import Producto

class IndexView(generic.ListView):
    template_name = "productos/index.html"
    context_object_name = "productos"
    
    def get_queryset(self):
        return Producto.objects.all()
    
class DetailView(generic.DetailView):
    model = Producto
    template_name = "productos/detail.html"

def index(request):
    productos = Producto.objects.all()
    
    data = {
        "productos" : productos
    }
    
    return render(request, "productos/index.html", data)

def detail(request, pk):
    
    producto = get_object_or_404(Producto, pk=pk)
    
    data = {
        "producto" : producto
    }
    
    return render(request, "productos/detail.html", data)

def agregar(request, pk):
    
    producto = get_object_or_404(Producto, pk=pk)
    
    producto.cantidad = producto.cantidad + 1
    
    producto.save()
    
    data = {
        "producto" : producto
    }
    
    return render(request, "productos/detail.html", data)

def quitar(request, pk):
    
    producto = get_object_or_404(Producto, pk=pk)
    
    producto.cantidad = producto.cantidad - 1
    
    producto.save()
    
    data = {
        "producto" : producto
    }
    
    return render(request, "productos/detail.html", data)


def nuevo(request):    
    return render(request, "productos/nuevo.html", {})

def editar(request, pk):   
    
    producto = get_object_or_404(Producto, pk=pk)
    
    data = {
        "producto" : producto
    }
    
    try:
        nombre = request.POST["nombre"]
        producto.nombre = nombre
        producto.save()        
        
        return render(request, "productos/detail.html", data)
        
    except:        
        pass
    
    return render(request, "productos/editar.html", data)

def guardar(request):  
    
    try:
        new = request.POST["nombre"]
    
    except (KeyError, "No se recibio el parametro nombre"):
        data = {
            "error_msj" : "No se pudo guardar el registro"
        }
        
        return render(request, 'productos/nuevo.html', data)
    
    else:    
        producto = Producto(nombre=new)
        producto.save()
    
    return HttpResponseRedirect(reverse('productos:detail', args=(producto.id,)))

productos/templates/productos/detail.html
<h1>{{ producto.nombre }}</h1>
<br>
Descripcion: {{ producto.descripcion }}
<br>
Categoria: {{ producto.categoria }}
<br>
Cantidad: {{ producto.cantidad }}
<br>
Precio: {{ producto.precio }}
<br>
<a href="{%url 'productos:nuevo' %}">Nuevo</a>
<a href="{%url 'productos:editar' producto.id %}">Modificar</a>
<a href="{%url 'productos:agregar' producto.id %}">Agregar</a>
<a href="{%url 'productos:quitar' producto.id %}">Quitar</a>

productos/templates/productos/editar.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Nuevo Producto</title>
</head>
<body>
	<form action="{% url 'productos:editar' producto.id %}" method="post">
		
		{% csrf_token %}

		<input type="hidden" name="pk" value="{{ producto.id }}">
		Nombre del Producto:
		<input type="text" name="nombre" value="{{ producto.nombre }}">


		<input type="submit" value="Guardar">

	</form>
</body>
</html>

productos/templates/productos/index.html
<!doctype html>
<html lang="en">
  <head>
    <title>Hello, world!</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />

  </head>
  <body>
    <h1>Listado de productos</h1>
	<ul>
		{% for prod in productos %}
		<li><a href="{% url 'productos:detail' prod.id %}">{{prod.nombre}}</a></li>
		{% endfor %}
	</ul>

	<script type="text/javascript" src="{%  static 'js/jquery-3.2.1.min.js' %}"></script>
	<script type="text/javascript" src="{%  static 'js/popper.min.js' %}"></script>
	<script type="text/javascript" src="{%  static 'js/bootstrap.min.js' %}"></script>
	
  </body>
</html>

productos/templates/productos/nuevo.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Nuevo Producto</title>
</head>
<body>
	<form action="{% url 'productos:guardar' %}" method="post">
		
		{% csrf_token %}
		Nooombre del Producto:
		<input type="text" name="nombre">


		<input type="submit" value="Guardar">

	</form>
</body>
</html>